openapi: 3.0.0
info:
  title: Bookstore
  description: My demo bookstore
  version: 0.0.1

servers:
  - url: http://localhost:8080/v1
    description: Local development environment
  - url: https://bookstore.hochbichler.at/v1
    description: Production environment

security:
  - basicAuth: []

paths:
  /books:
    get:
      operationId: findAllBooks
      summary: Return all books
      description: Retrieve all books from the store
      responses:
        '200':
          description: if OK, returns a list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
    post:
      operationId: addNewBook
      summary: Add a new book
      description: Adds a new book to the store
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBook'
      responses:
        '200':
          description: book response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    NewBook:
      properties:
        name:
          type: string
      required:
        - name
    Book:
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    GeneralError:
      properties:
        code:
          type: string
        description:
          type: string
      required:
        - code
        - description